
180 CONSTANT DIR_SIZE

CREATE  DIR_STOR  DIR_SIZE ALLOT
CREATE  DIRF_STOR  DIR_SIZE 10 + ALLOT

0 VALUE DBG_CURFILE

: DBG_CURFILE,
  HERE TO DBG_CURFILE
  CURFILE @ 1+ C@ [CHAR] : = 1 OR
  IF      CURFILE @ ASCIIZ> S",
  ELSE    DIR_STOR DIR_SIZE GetCurrentDirectoryA DROP
          DIR_STOR ASCIIZ> DIRF_STOR $! 
                     S" \" DIRF_STOR $+!
        CURFILE @ ASCIIZ>  DIRF_STOR $+!
        DIRF_STOR COUNT  S",
  THEN
;
